Changes for django 1.10 + installation instructions.
evykassirer/whatprivilege pull request #13
Opened 2016-12-23 10:28 UTC by DrDub

Instructions to run a dev version. Tested on python2.7.

2016-12-24 03:37 UTC, evykassirer requested changes
love this! thanks for adding this - just a few nit comments

I'd love to know - do you plan on using this for something?

2016-12-24 03:37 UTC, evykassirer commented on README.md
> +- edit django_project/sample_settings.py into settings.py
"rename `django_project/sample_settings.py` to `django_project/settings.py`" would be more clear I think

2016-12-24 03:37 UTC, evykassirer commented on README.md
> +- python manage.py runserver
then run these commands:
```
python manage.py migrate --run-syncdb
python manage.py loaddata data.json
python manage.py runserver
```

(the backticks make it a bit easier to see at a glance that you're running a command)

2016-12-24 03:37 UTC, evykassirer commented on README.md
> +
can you add an instruction to install the right django version? that was the one bump I encountered when trying to get it run locally

2016-12-27 00:58 UTC, evykassirer approved these changes

2016-12-27 00:58 UTC, merged

2016-12-27 00:58 UTC, evykassirer commented
thanks!

2016-12-27 00:59 UTC, DrDub commented
Answering your question, I do not plan to use this at the moment, but it seems a nice project and worth improving.